export const ADD_INGRENDIENT = 'ADD_INGRENDIENT';
export const REMOVE_INGRENDIENT = 'REMOVE_INGRENDIENT';
export const SET_INGRENDIENT = 'SET_INGRENDIENT';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';